kitchen/urls.py
from django.urls import path

from kitchen.views import (
       index,
       DishTypeListView,
       DishTypeDetailView,
       DishTypeCreateView,
       DishTypeUpdateView,
       DishTypeDeleteView,
       CookListView,
       CookDetailView,
       CookCreateView,
       DishListView,
       DishDetailView,
       DishCreateView,
       DishUpdateView,
       DishDeleteView,
)

urlpatterns = [
       path("", index, name="index"),

       path(
              "dish-types/",
              DishTypeListView.as_view(),
              name="dish-type-list"
       ),
       path(
              "dish-types/<int:pk>/",
              DishTypeDetailView.as_view(),
              name="dish-type-detail"
       ),
       path(
              "dish-types/create/",
              DishTypeCreateView.as_view(),
              name="dish-type-create"
       ),
       path(
              "dish-types/<int:pk>/update/",
              DishTypeUpdateView.as_view(),
              name="dish-type-update"
       ),
       path(
              "dish-types/<int:pk>/delete/",
              DishTypeDeleteView.as_view(),
              name="dish-type-delete"
       ),

       path(
              "cooks/",
              CookListView.as_view(),
              name="cook-list"
       ),
       path(
              "cooks/<int:pk>/",
              CookDetailView.as_view(),
              name="cook-detail"
       ),
       path(
              "cooks/create/",
              CookCreateView.as_view(),
              name="cook-create"
       ),

       path(
              "dishes/",
              DishListView.as_view(),
              name="dish-list"
       ),
       path(
              "dishes/<int:pk>/",
              DishDetailView.as_view(),
              name="dish-detail"
       ),
       path(
              "dishes/create/",
              DishCreateView.as_view(),
              name="dish-create"
       ),
       path(
              "dishes/<int:pk>/update/",
              DishUpdateView.as_view(),
              name="dish-update"
       ),
       path(
              "dishes/<int:pk>/delete/",
              DishDeleteView.as_view(),
              name="dish-delete"
       ),
]

app_name = "kitchen"

shynok/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
       path('admin/', admin.site.urls),
       path("", include("kitchen.urls", namespace="kitchen")),
       path("accounts/", include("django.contrib.auth.urls"))
]  + debug_toolbar_urls()

kitchen/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.PositiveIntegerField(
        default=0,
        null=False,
        blank=False,
    )

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(
        max_length=255,
        null=False,
        blank=False,
    )
    description = models.CharField(max_length=255)
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
    )
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="type_dishes",
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes",
    )

    class Meta:
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name} {self.price}"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Cook, Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish name"
            }
        )
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by cook username"
            }
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish type name"
            }
        )
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    CookCreationForm,
    DishForm,
    DishSearchForm,
    CookSearchForm,
    DishTypeSearchForm,
)
from kitchen.models import Cook, DishType, Dish


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_cooks = Cook.objects.count()
    num_type_dishes = DishType.objects.count()
    num_dishes = Dish.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_cooks": num_cooks,
        "num_type_dishes": num_type_dishes,
        "num_dishes": num_dishes,
        "segment": "index",
        "num_visits": num_visits + 1,
    }
    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 10

    def get_context_data(
        self, *, object_list=..., **kwargs
    ):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "kitchen/dish_type_detail.html"
    context_object_name = "dish_type_detail"


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_confirm_delete.html"


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 10

    def get_context_data(
        self, *, object_list=..., **kwargs
    ):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 10

    def get_context_data(
        self, *, object_list=..., **kwargs
    ):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            ).order_by("name")
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")

templates/kitchen/cook_detail.html
{% extends "layouts/base.html" %}

{% block content %}
	<h1>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</h1>
  <div class="ml-3">
    <h3>{{ cook.email }}</h3>
    <p>{{ cook.years_of_experience }} years of experience</p>
    <h4>Can cook:</h4>
    {% for meal in cook.dishes.all %}
      <hr>
      <p class="text-muted">{{ meal.name }}</p>
      {% empty %}
        <p>No Dishes</p>
  {% endfor %}

  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
	<h1>Create cook</h1>
  {% include 'includes/confirm_form.html' with form=form %}
{% endblock %}

templates/kitchen/cook_list.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <div style="float: right;">
                    {% include 'includes/search_form.html' with form=form %}
                </div>
                  <h4 class="card-title ">Cook list</h4>
                  <p class="card-category">our staff</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                  {% if cook_list %}
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Username
                          <a class="btn btn-sm" href="{% url 'kitchen:cook-create' %}">+</a>
                        </th>
                        <th>
                          Full name
                        </th>
                        <th>
                          Experience
                        </th>
                        <th>
                          ID
                        </th>
                      </thead>
                      <tbody>
                      {% for cook in cook_list %}
                        <tr>
                          <td>
                            <a href="{{ cook.get_absolute_url }}">{{ cook.username }}</a>
                          </td>
                          <td>
                            {{ cook.first_name }} {{ cook.last_name }}
                          </td>
                          <td>
                            {{ cook.years_of_experience }} year{{ cook.years_of_experience|pluralize }}
                          </td>
                          <td>
                            {{ cook.id }}
                          </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                  {% else %}
                    <p>There are no cooks in Kitchen</p>
                  {% endif %}
              </div>
            </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
	<h1>Delete Dish</h1>
  <p>Are you sure you want to delete the dish: {{ dish.name }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
  <a href="{% url 'kitchen:dish-list' %}" class="btn btn-secondary">No thanks</a>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "layouts/base.html" %}

{% block content %}
	<h1>{{ dish.name }} <a class="btn btn-secondary" style="float: right" href="{% url 'kitchen:dish-update' pk=dish.id %}">Edit</a></h1>
  <div class="ml-3">
    <h3>This is {{ dish.dish_type }}</h3>
    <p>Description: {{ dish.description }}</p>
    <p>Price: {{ dish.price }}</p>
    <h4>Who can cook:</h4>
    {% for cook in dish.cooks.all %}
      <hr>
      <p class="text-muted">{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</p>
    {% endfor %}

  </div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
	<h1>{{ object|yesno:"Update, Create" }} Dish</h1>
  {% include 'includes/confirm_form.html' with form=form %}
{% endblock %}

templates/kitchen/dish_list.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <div style="float: right;">
                    {% include 'includes/search_form.html' with form=form %}
                  </div>
                  <h4 class="card-title ">Dish list</h4>
                  <p class="card-category">what you want to try?</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                  {% if dish_list %}
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Dish
                          <a class="btn btn-sm" href="{% url 'kitchen:dish-create' %}">+</a>
                        </th>
                        <th>
                          Price
                        </th>
                        <th>
                          Update
                        </th>
                        <th>
                          Delete
                        </th>
                        <th>
                          ID
                        </th>
                      </thead>
                      <tbody>
                      {% for dish in dish_list %}
                        <tr>
                          <td>
                            <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
                          </td>
                          <td>
                            {{ dish.price }}
                          </td>
                          <td>
                            <a href="{% url 'kitchen:dish-update' pk=dish.id %}">Update</a>
                          </td>
                          <td>
                            <a href="{% url 'kitchen:dish-delete' pk=dish.id %}">DELETE</a>
                          </td>
                          <td>
                            {{ dish.id }}
                          </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                  {% else %}
                    <p>There are no dishes in Kitchen</p>
                  {% endif %}
              </div>
            </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
	<h1>Delete Dish Type</h1>
  <p>Are you sure you want to delete the dish type: {{ dishtype }}</p>
  <p><i>All related dishes will become of some unspecified type</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-secondary">No thanks</a>
{% endblock %}

templates/kitchen/dish_type_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>{{ dish_type_detail.name }} <a class="btn btn-secondary" style="float: right" href="{% url 'kitchen:dish-type-update' pk=dish_type_detail.id %}">Edit</a></h1>
  <div class="ml-3">
    <h3>Dishes:</h3>
    {% for dish in dish_type_detail.type_dishes.all %}
      <hr>
      <p class="text-muted">{{ dish.name }}</p>
    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
    
  </div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "layouts/base.html" %}

{% block content %}
	<h1>{{ object|yesno:"Update, Create" }} Dish Type</h1>
  {% include 'includes/confirm_form.html' with form=form %}
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <div style="float: right;">
                    {% include 'includes/search_form.html' with form=form %}
                  </div>
                  <h4 class="card-title ">Dish types list</h4>
                  <p class="card-category">with examples inside</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                  {% if dish_type_list %}
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Type
                          <a class="btn btn-sm" href="{% url 'kitchen:dish-type-create' %}">+</a>
                        </th>
                        <th>
                          Update
                        </th>
                        <th>
                          Delete
                        </th>
                        <th>
                          ID
                        </th>
                      </thead>
                      <tbody>
                      {% for dish_type in dish_type_list %}
                        <tr>
                          <td>
                            <a href="{% url 'kitchen:dish-type-detail' pk=dish_type.id %}">{{ dish_type.name }}</a>
                          </td>
                          <td>
                            <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">Update</a>
                          </td>
                          <td>
                            <a href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">DELETE</a>
                          </td>
                          <td>
                            {{ dish_type.id }}
                          </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                  {% else %}
                    <p>There are no dish types in Kitchen</p>
                  {% endif %}
              </div>
            </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/index.html
{% extends "layouts/base.html" %}

{% block title %} Shynok {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <h1>Welcome to our kitchen</h1>
  <br>
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-symbols-outlined">chef_hat</i>
            </div>
            <p class="card-category">Cooks</p>
            <h3 class="card-title">{{ num_cooks }}
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons"></i>Best chefs
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-symbols-outlined">menu_book</i>
            </div>
            <p class="card-category">Dish Types</p>
            <h3 class="card-title">{{ num_type_dishes }}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons"></i> Variety of dishes
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-symbols-outlined">restaurant</i>
            </div>
            <p class="card-category">Dishes</p>
            <h3 class="card-title">{{ num_dishes }}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons"></i> Must Try!
            </div>
          </div>
        </div>
      </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}